### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by kisvegabor** [littlevgl/lv_i18n#15]
I update the readme to make it more consistent and clear for users who are not so familiar with i18n yet.
Here it is: https://github.com/littlevgl/lv_i18n/blob/readme_kisvegabor/README.md

Still, there are some TODOs in it.

**Comment by puzrin** [comment]
Ok. Let me know when done, i'll post comments

**Comment by kisvegabor** [comment]
Only [one section](https://github.com/littlevgl/lv_i18n/blob/readme_kisvegabor/README.md#follow-modifications-in-the-source-code) is missing so you can add the comments.

**Comment by puzrin** [comment]
I've finished preliminary review. Let me know after update - i'll do the second pass.

PS. Please squash all into single commit after edit - it will be more easy find place to leave comments.

**Comment by kisvegabor** [comment]
I'll update it soon.

**Comment by puzrin** [comment]
Note about "intro". I don't know how to explain... goal is to make it short and more "recognizable". To help use think "yeah, i know what's that and wish to read details". Ideally, all should fix into 1 phrase. Max - 2 phrases. If user can't "switch on" immediately, it will not continue.

PS. Probably, my initial version was not perfect to. On review i don't keep in mind anything and read all with "clean brain". Don't accept any comment as personal critics.

**Comment by kisvegabor** [comment]
I also don't think my version is better. It just was easier to follow for me.

**Comment by kisvegabor** [comment]
I fixed some things: https://github.com/littlevgl/lv_i18n/commit/c8ae442e219e996c55a947b5dfade2bff46ba8f9

The introduction is not complete yet. IMO somehow the plural support should be highlighted be didn't find a way yet how to write it.

**Comment by puzrin** [comment]
> The introduction is not complete yet. IMO somehow the plural support should be highlighted be didn't find a way yet how to write it.

Novices will not understand how important is this. For experienced users this feature is essential. I think, is safe to skip this from intro.

Anyway, this package has no alternatives at all :)

**Comment by kisvegabor** [comment]
Do you mean to emphasize more that it something really cool? :)

**Comment by puzrin** [comment]
https://github.com/littlevgl/lv_i18n/commit/5cca0bef0137d95e3835ef378d274bdfa1b79af3

I pushed changes into separate branch instead of comments. Feel free to use of skip anything.

**Comment by kisvegabor** [comment]
Your intro text look good! I will check in details soon

**Comment by kisvegabor** [comment]
I formatted the [C API](https://github.com/littlevgl/lv_i18n/blob/readme_kisvegabor/README.md#c-api) section a little bit.

What is still missing: 
- [Follow modifications in the source code](https://github.com/littlevgl/lv_i18n/blob/readme_kisvegabor/README.md#follow-modifications-in-the-source-code) section. I didn't tested it yet.
- Maybe improve shoort description in the beginning.

**Comment by puzrin** [comment]
Looks nice.

Probably mistyped: `praslation` => `translation`

**Comment by kisvegabor** [comment]
Fixed, thank you!
